language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build:staging
  - npm run build
deploy:
  - provider: pages
    repo: mkolman/game-utilities-staging
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist_staging
    keep_history: true
    on:
      branch: staging
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist
    keep_history: true
    on:
      branch: master
