title: Play Now

baseurl: "/game-utilities"
url: "https://www.kolman.si"

color:
  theme: "#D32F2F"
  bg: "#EEEEEE"

sharing:
  description: "Helper apps to play board games."
  img: "/img/splash.png"

# Build settings
markdown: kramdown
sass:
    style: compressed


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
